// <auto-generated />
using IoT.Capstone.KeyGen.Admin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IoT.Capstone.KeyGen.Admin.Migrations
{
    [DbContext(typeof(KeyGenContext))]
    partial class KeyGenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IoT.Capstone.KeyGen.Admin.Models.EdxUser", b =>
                {
                    b.Property<int>("Uid");

                    b.Property<string>("EdxId")
                        .IsRequired();

                    b.HasKey("Uid");

                    b.HasIndex("EdxId")
                        .IsUnique();

                    b.ToTable("EdxUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
